### PR TITLE
Added automatic multi-workspace support

### PR DESCRIPTION
**Pull request by steveyegge**
Cody Emacs now runs a separate Agent instance for every open workspace. This happens automatically, seamlessly, and lazily. 

I typically open ~100 files on startup with a `desktop-read`, and Cody intentionally doesn't start in all of them. It waits until you `cody-login', and then only starts up Agent connections in workspaces when you switch to them for the first time.

You can use `M-x cody-dashboard` to see your active connections:

image

The implementation change was that we now keep a hashmap of new `cody-workspace` objects, one per repo (or workspace/project), keyed on the workspace uri. They encapsulate all the connection/Agent state that used to be global.

Workspaces are garbage collected (and shut down) a configurable time after `cody-gc-workspace-timeout` seconds (5 min default), to keep Node processes from accumulating.

This needs more customizability; e.g.,

- the rules by which files and workspaces are eligible to be Cody-enabled automatically
- an option to have it only enable Cody in workspaces on demand

I'm sure it also needs more testing. But the basic happy path seems to be working well.

# Other bug fixes

This PR fixes a number of other bugs that snuck in to the giant PR that brought completions back, integration testing, and so on. This includes some infinite recursions and other unhappy paths.

# Test Plan

All this stuff needs testing.

### CODE REVIEW

**Comment by keegancsmith** [comment]
With https://github.com/sourcegraph/emacs-cody/pull/32 I can run cody in emacs! Thanks!

**Review by keegancsmith — APPROVED** [review]
I skimmed over the code. However, I checked this out and I got completions working! So gonna approve :)

**Comment by keegancsmith** [comment]
The main issue I have run into now while testing is that when logging into cody emacs freezes. So first time switching to a new project root everything freezes for a few seconds. This might be more pronounced for me than you due to latencies of living in South Africa and our servers being in USA. I'd prefer this to be async. Alternatively to make it possible for it to work like eglot where I have to run something like `eglot-ensure` to start up cody, and then to make it magic I add that as a hook.

**Review by dominiccooney — APPROVED** [review]
LGTM

**Pull request merged**
